server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://211.159.217.246:3306/wayne-space
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  redis:
    database: 0
    host: 211.159.217.246
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0

  kafka:
    bootstrap-servers: 211.159.217.246:9092
    consumer:
      group-id: admin-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  dubbo:
    application:
      name: admin-provider
    registry:
      protocol: zookeeper
      address: 211.159.217.246:2181
      timeout: 60000
    protocol:
      name: dubbo
      port: 20881
      host: 211.159.217.246
    scan: com.wayne.dubbo
