spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.17.0.5:3306/yojulife
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  redis:
    database: 0
    host: 172.17.0.5
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    pool:
      max-active: 8
      max-idle: 8
      max-wait: 1
      min-idle: 0

  kafka:
    bootstrap-servers: 172.17.0.5:9092
    consumer:
      group-id: test-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  dubbo:
    application:
      name: admin-provider
    registry:
      protocol: zookeeper
      address: 172.17.0.5:2181
      timeout: 60000
    protocol:
      name: dubbo
      port: 20881
      host: 172.17.0.5.246
    scan: com.wayne.dubbo